### ISSUE TITLE
Ideas about Portable version?

### ISSUE THREAD

**Issue by andzi** [ssborbis/ContextSearch-Native-App#1]
Ideas about Portable version in some format?

- https://portableapps.com/about/what_is_a_portable_app
- https://portableapps.com/development/portableapps.com_format

**Comment by ssborbis** [comment]
Been a while since I worked on this, but I believe webextensions nativeMessaging specifically requires access to the registry under Windows. That may prevent 'portability'

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging

What do you have in mind?

**Comment by andzi** [comment]
Looking for some customisation ways. Probably yes, bad idea. Let's close.
